cd ~
sudo yum update -y
sudo yum install git -y

git --version

cd ~/projects
git clone https://github.com/JordanRino/Smart-Report-Analyst.git smart-report-analyst
cd smart-report-analyst


cd ~/projects/smart-report-analyst

to install  uv - curl -LsSf https://astral.sh/uv/install.sh | sh

if uv is already installed - export PATH="$HOME/.local/bin:$PATH"

uv sync

chainlit run src/smart_report_analyst/ui/chainlit/manager.py --host 0.0.0.0 --port 8000

