cd ~
sudo yum update -y
sudo yum install git -y

git --version

cd ~/projects
git clone https://github.com/JordanRino/Smart-Report-Analyst.git smart-report-analyst
cd smart-report-analyst


cd ~/projects/smart-report-analyst
python3 -m venv venv
source venv/bin/activate

pip install --upgrade pip
pip install uv

uv sync --active

chainlit run src/smart_report_analyst/ui/chainlit/manager.py --host 0.0.0.0 --port 8000

